### ISSUE TITLE
WPA2 Not connecting - WPA okay. DD-WRT

### ISSUE THREAD

**Issue by Scales82** [universam1/iSpindel#225] opened 2018-10-18 07:58 UTC
I'm using a linksys DD-WRT router. none of my ispindels like to connect to my network using wpa2. as soon as i switch to wpa it works fine. Any ideas?

**Comment by universam1** [comment] 2018-10-18 08:53
WPA2 works fine for me, try another access point

**Comment by Scales82** [comment] 2018-10-18 11:01
I am sorry, I only own one....

**Comment by universam1** [comment] 2018-10-24 19:40
you might try the new 6.0.2 using the new SDK

**Comment by Scales82** [comment] 2018-10-29 03:59
I’ll reflash when I am home next and try again (out of country) I’ll let you know.
Does that mean 6.02 has been updated?

**Comment by brendongough** [comment] 2018-12-06 02:52
I've had mixed results with different wifi routers, I restored to using an old Apple Airport Extreme (802.11n version) as my express and Mikrotik didn't reliably work. I found this cross platform on the same device (BrewPiLess). I have not tested this on 6.0.2 yet or the BrewPiLess 3.4 though.

**Comment by Scales82** [comment] 2018-12-17 01:06
I ended up changing my routers firmware back to stock Linksys firmware, connects fine now. Still an outstanding issue though I believe

**Comment by Scales82** [comment] 2018-12-17 04:05
Okay, so an update,
I've gone back to DD-WRT, using the latest beta for my device. (v37961). The problem still exists, but I gave the ispindel ESP a static IP reservation in the DD-WRT DHCP server. Now it connects using WPA2 no problem!
![capture](https://user-images.githubusercontent.com/44252921/50065925-26c84400-020d-11e9-8447-27388523de80.PNG)

**Comment by universam1** [comment] 2018-12-17 08:34
Hence it is obviously not an WPA2 issue at all, since this is authentication and not dhcp related.

**Comment by universam1** [comment] 2018-12-19 19:21
There is nothing we can do in this regard since it first of all is not confirmed with other access points, More over that would even be outside of this project using the SDK from Espressif eventually that does the hard lifting. If there is more to add on it feel free, for now I will close this issue since not a bug or so

**Closed by universam1** 2018-12-19 19:21 UTC
